target_column: diagnosis

columns:
  id: integer
  diagnosis: string
  radius_mean: float
  texture_mean: float
  perimeter_mean: float
  area_mean: float
  smoothness_mean: float
  compactness_mean: float
  concavity_mean: float
  concave_points_mean: float
  symmetry_mean: float
  fractal_dimension_mean: float
  radius_se: float
  texture_se: float
  perimeter_se: float
  area_se: float
  smoothness_se: float
  compactness_se: float
  concavity_se: float
  concave_points_se: float
  symmetry_se: float
  fractal_dimension_se: float
  radius_worst: float
  texture_worst: float
  perimeter_worst: float
  area_worst: float
  smoothness_worst: float
  compactness_worst: float
  concavity_worst: float
  concave_points_worst: float
  symmetry_worst: float
  fractal_dimension_worst: float

types:
  id: "integer"
  diagnosis: "categorical"
  radius_mean: "float"
  texture_mean: "float"
  perimeter_mean: "float"
  area_mean: "float"
  smoothness_mean: "float"
  compactness_mean: "float"
  concavity_mean: "float"
  concave_points_mean: "float"
  symmetry_mean: "float"
  fractal_dimension_mean: "float"
  radius_se: "float"
  texture_se: "float"
  perimeter_se: "float"
  area_se: "float"
  smoothness_se: "float"
  compactness_se: "float"
  concavity_se: "float"
  concave_points_se: "float"
  symmetry_se: "float"
  fractal_dimension_se: "float"
  radius_worst: "float"
  texture_worst: "float"
  perimeter_worst: "float"
  area_worst: "float"
  smoothness_worst: "float"
  compactness_worst: "float"
  concavity_worst: "float"
  concave_points_worst: "float"
  symmetry_worst: "float"
  fractal_dimension_worst: "float"

constraints:
  radius_mean:
    min: 5.0
    max: 50.0
  perimeter_mean:
    min: 40.0
    max: 200.0
  area_mean:
    min: 100.0
    max: 2500.0
  concave_points_mean:
    min: 0.0
    max: 0.5
  diagnosis:
    values: ["M", "B"]

missing_values: ["", "NA", "NaN", "null", "?"]