services:
  - name: disease-predictor
    type: web
    runtime: python
    plan: free
    envVars:
      - key: PORT
        value: 8080
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true