columns:
  Pregnancies: int
  Glucose: float
  BloodPressure: float
  SkinThickness: float
  Insulin: float
  BMI: float
  DiabetesPedigreeFunction: float
  Age: int
  Outcome: int

types:
  Pregnancies: "integer"
  Glucose: "float"
  BloodPressure: "float"
  SkinThickness: "float"
  Insulin: "float"
  BMI: "float"
  DiabetesPedigreeFunction: "float"
  Age: "integer"
  Outcome: "integer"

constraints:
  Pregnancies:
    min: 0
    max: 20
  Glucose:
    min: 50
    max: 250
  BloodPressure:
    min: 40
    max: 150
  SkinThickness:
    min: 0
    max: 99
  Insulin:
    min: 0
    max: 800
  BMI:
    min: 10.0
    max: 60.0
  DiabetesPedigreeFunction:
    min: 0.1
    max: 2.5
  Age:
    min: 18
    max: 100
  Outcome:
    values: [0, 1]